name: ubuntu

on:
    workflow_dispatch:
    #push:
    #    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: install glfw openmp
          working-directory: .
          run: |
              sudo apt-get update
              sudo apt-get install libglfw3 libglfw3-dev
              sudo apt-get install libomp-dev
              sudo apt-get install libeigen3-dev

        - name: build Demo
          run: |
              mkdir build
              cd build
              cmake ..
              make
          working-directory: ./project3d/Demo

        - name: build test
          run: |
              mkdir build
              cd build
              cmake ..
              make
          working-directory: ./test/math

        - name: exec test
          run: ./Program
          working-directory: ./test/math/build
