name: ubuntu

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: install glfw openmp
          working-directory: .
          run: |
              sudo apt-get install libglfw3 libglfw3-dev
              sudo apt-get install libomp-dev

        - name: build Demo
          working-directory: ./project3d/Demo
          run: |
              mkdir build
              cd build
              cmake ..
              make


    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
        - name: execute Demo
          working-directory: ./project3d/Demo/build
          run: ./Program

